import dayjs from "dayjs"
import { ASSET_CLASSES } from "./constants"
import { AssetType, Transaction } from "./types"

export const ASSETS: AssetType[] = [
  {
    id: 1,
    name: ASSET_CLASSES.CASH,
    percent: 25,
    amount: 24000,
    returns: 10000,
    percentReturn: 11,
    color: "#5CAAAA",
  },
  {
    id: 2,
    name: ASSET_CLASSES.CRYPTO,
    percent: 25,
    amount: 24000,
    returns: 10000,
    percentReturn: 11,
    color: "#8B5CF6",
  },
  {
    id: 3,
    name: ASSET_CLASSES.STOCKS,
    percent: 25,
    amount: 24000,
    returns: 10000,
    percentReturn: 11,
    color: "#5388FF",
  },
  {
    id: 4,
    name: ASSET_CLASSES.BONDS,
    percent: 25,
    amount: 24000,
    returns: 10000,
    percentReturn: 11,
    color: "#F0BD66",
  },
]

export const TRANSACTIONS: Transaction[] = [
  {
    id: 1,
    transactionId: "JDEUAYYWTQ",
    amount: 38525,
    date: dayjs().format(),
    type: "transfer",
    amountTendered: 250,
    amountRecieved: 177.9,
    fees: 5,
    description: "Bills Payment",
    status: "approved",
  },
  {
    id: 2,
    transactionId: "JDEUAYYWTQ",
    amount: 38525,
    date: dayjs().format(),
    type: "transfer",
    amountTendered: 250,
    amountRecieved: 177.9,
    fees: 5,
    description: "Bills Payment",
    status: "failed",
  },
  {
    id: 3,
    transactionId: "JDEUAYYWTQ",
    amount: 38525,
    date: dayjs().format(),
    type: "transfer",
    amountTendered: 250,
    amountRecieved: 177.9,
    fees: 5,
    description: "Bills Payment",
    status: "pending",
  },
  {
    id: 4,
    transactionId: "JDEUAYYWTQ",
    amount: 38525,
    date: dayjs().format(),
    type: "transfer",
    amountTendered: 250,
    amountRecieved: 177.9,
    fees: 5,
    description: "Bills Payment",
    status: "approved",
  },
  {
    id: 5,
    transactionId: "JDEUAYYWTQ",
    amount: 38525,
    date: dayjs().format(),
    type: "transfer",
    amountTendered: 250,
    amountRecieved: 177.9,
    fees: 5,
    description: "Bills Payment",
    status: "approved",
  },
  {
    id: 6,
    transactionId: "JDEUAYYWTQ",
    amount: 38525,
    date: dayjs().format(),
    type: "transfer",
    amountTendered: 250,
    amountRecieved: 177.9,
    fees: 5,
    description: "Bills Payment",
    status: "approved",
  },
  {
    id: 7,
    transactionId: "JDEUAYYWTQ",
    amount: 38525,
    date: dayjs().format(),
    type: "transfer",
    amountTendered: 250,
    amountRecieved: 177.9,
    fees: 5,
    description: "Bills Payment",
    status: "approved",
  },
  {
    id: 8,
    transactionId: "JDEUAYYWTQ",
    amount: 38525,
    date: dayjs().format(),
    type: "transfer",
    amountTendered: 250,
    amountRecieved: 177.9,
    fees: 5,
    description: "Bills Payment",
    status: "approved",
  },
]
